// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package season

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Season {
	return predicate.Season(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Season {
	return predicate.Season(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Season {
	return predicate.Season(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Season {
	return predicate.Season(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Season {
	return predicate.Season(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Season {
	return predicate.Season(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Season {
	return predicate.Season(sql.FieldLTE(FieldID, id))
}

// SeriesID applies equality check predicate on the "series_id" field. It's identical to SeriesIDEQ.
func SeriesID(v int64) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldSeriesID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldTitle, v))
}

// FirstAired applies equality check predicate on the "first_aired" field. It's identical to FirstAiredEQ.
func FirstAired(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldFirstAired, v))
}

// LastAired applies equality check predicate on the "last_aired" field. It's identical to LastAiredEQ.
func LastAired(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldLastAired, v))
}

// SeriesIDEQ applies the EQ predicate on the "series_id" field.
func SeriesIDEQ(v int64) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldSeriesID, v))
}

// SeriesIDNEQ applies the NEQ predicate on the "series_id" field.
func SeriesIDNEQ(v int64) predicate.Season {
	return predicate.Season(sql.FieldNEQ(FieldSeriesID, v))
}

// SeriesIDIn applies the In predicate on the "series_id" field.
func SeriesIDIn(vs ...int64) predicate.Season {
	return predicate.Season(sql.FieldIn(FieldSeriesID, vs...))
}

// SeriesIDNotIn applies the NotIn predicate on the "series_id" field.
func SeriesIDNotIn(vs ...int64) predicate.Season {
	return predicate.Season(sql.FieldNotIn(FieldSeriesID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Season {
	return predicate.Season(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Season {
	return predicate.Season(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Season {
	return predicate.Season(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Season {
	return predicate.Season(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Season {
	return predicate.Season(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Season {
	return predicate.Season(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Season {
	return predicate.Season(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Season {
	return predicate.Season(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Season {
	return predicate.Season(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Season {
	return predicate.Season(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Season {
	return predicate.Season(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Season {
	return predicate.Season(sql.FieldContainsFold(FieldTitle, v))
}

// FirstAiredEQ applies the EQ predicate on the "first_aired" field.
func FirstAiredEQ(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldFirstAired, v))
}

// FirstAiredNEQ applies the NEQ predicate on the "first_aired" field.
func FirstAiredNEQ(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldNEQ(FieldFirstAired, v))
}

// FirstAiredIn applies the In predicate on the "first_aired" field.
func FirstAiredIn(vs ...time.Time) predicate.Season {
	return predicate.Season(sql.FieldIn(FieldFirstAired, vs...))
}

// FirstAiredNotIn applies the NotIn predicate on the "first_aired" field.
func FirstAiredNotIn(vs ...time.Time) predicate.Season {
	return predicate.Season(sql.FieldNotIn(FieldFirstAired, vs...))
}

// FirstAiredGT applies the GT predicate on the "first_aired" field.
func FirstAiredGT(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldGT(FieldFirstAired, v))
}

// FirstAiredGTE applies the GTE predicate on the "first_aired" field.
func FirstAiredGTE(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldGTE(FieldFirstAired, v))
}

// FirstAiredLT applies the LT predicate on the "first_aired" field.
func FirstAiredLT(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldLT(FieldFirstAired, v))
}

// FirstAiredLTE applies the LTE predicate on the "first_aired" field.
func FirstAiredLTE(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldLTE(FieldFirstAired, v))
}

// LastAiredEQ applies the EQ predicate on the "last_aired" field.
func LastAiredEQ(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldEQ(FieldLastAired, v))
}

// LastAiredNEQ applies the NEQ predicate on the "last_aired" field.
func LastAiredNEQ(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldNEQ(FieldLastAired, v))
}

// LastAiredIn applies the In predicate on the "last_aired" field.
func LastAiredIn(vs ...time.Time) predicate.Season {
	return predicate.Season(sql.FieldIn(FieldLastAired, vs...))
}

// LastAiredNotIn applies the NotIn predicate on the "last_aired" field.
func LastAiredNotIn(vs ...time.Time) predicate.Season {
	return predicate.Season(sql.FieldNotIn(FieldLastAired, vs...))
}

// LastAiredGT applies the GT predicate on the "last_aired" field.
func LastAiredGT(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldGT(FieldLastAired, v))
}

// LastAiredGTE applies the GTE predicate on the "last_aired" field.
func LastAiredGTE(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldGTE(FieldLastAired, v))
}

// LastAiredLT applies the LT predicate on the "last_aired" field.
func LastAiredLT(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldLT(FieldLastAired, v))
}

// LastAiredLTE applies the LTE predicate on the "last_aired" field.
func LastAiredLTE(v time.Time) predicate.Season {
	return predicate.Season(sql.FieldLTE(FieldLastAired, v))
}

// HasSeries applies the HasEdge predicate on the "series" edge.
func HasSeries() predicate.Season {
	return predicate.Season(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SeriesTable, SeriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeriesWith applies the HasEdge predicate on the "series" edge with a given conditions (other predicates).
func HasSeriesWith(preds ...predicate.Series) predicate.Season {
	return predicate.Season(func(s *sql.Selector) {
		step := newSeriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEpisodes applies the HasEdge predicate on the "episodes" edge.
func HasEpisodes() predicate.Season {
	return predicate.Season(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EpisodesTable, EpisodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEpisodesWith applies the HasEdge predicate on the "episodes" edge with a given conditions (other predicates).
func HasEpisodesWith(preds ...predicate.Episode) predicate.Season {
	return predicate.Season(func(s *sql.Selector) {
		step := newEpisodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Season) predicate.Season {
	return predicate.Season(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Season) predicate.Season {
	return predicate.Season(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Season) predicate.Season {
	return predicate.Season(sql.NotPredicates(p))
}
