// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/predicate"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/schema/field"
)

// EpisodeUpdate is the builder for updating Episode entities.
type EpisodeUpdate struct {
	config
	hooks       []Hook
	mutation    *EpisodeMutation
	retryConfig sql.RetryConfig
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (_u *EpisodeUpdate) Where(ps ...predicate.Episode) *EpisodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSeasonID sets the "season_id" field.
func (_u *EpisodeUpdate) SetSeasonID(v int64) *EpisodeUpdate {
	_u.mutation.SetSeasonID(v)
	return _u
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableSeasonID(v *int64) *EpisodeUpdate {
	if v != nil {
		_u.SetSeasonID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *EpisodeUpdate) SetTitle(v string) *EpisodeUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableTitle(v *string) *EpisodeUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAirDate sets the "air_date" field.
func (_u *EpisodeUpdate) SetAirDate(v time.Time) *EpisodeUpdate {
	_u.mutation.SetAirDate(v)
	return _u
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (_u *EpisodeUpdate) SetNillableAirDate(v *time.Time) *EpisodeUpdate {
	if v != nil {
		_u.SetAirDate(*v)
	}
	return _u
}

// SetSeason sets the "season" edge to the Season entity.
func (_u *EpisodeUpdate) SetSeason(v *Season) *EpisodeUpdate {
	return _u.SetSeasonID(v.ID)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_u *EpisodeUpdate) Mutation() *EpisodeMutation {
	return _u.mutation
}

// ClearSeason clears the "season" edge to the Season entity.
func (_u *EpisodeUpdate) ClearSeason() *EpisodeUpdate {
	_u.mutation.ClearSeason()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EpisodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EpisodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EpisodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EpisodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EpisodeUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := episode.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Episode.title": %w`, err)}
		}
	}
	if _u.mutation.SeasonCleared() && len(_u.mutation.SeasonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Episode.season"`)
	}
	return nil
}

// WithRetryOptions sets the retry options for the update operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_u *EpisodeUpdate) WithRetryOptions(opts ...any) *EpisodeUpdate {
	_u.retryConfig.Options = opts
	return _u
}

func (_u *EpisodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
	}
	if _u.mutation.SeasonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.RetryConfig = _u.retryConfig
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EpisodeUpdateOne is the builder for updating a single Episode entity.
type EpisodeUpdateOne struct {
	config
	fields      []string
	hooks       []Hook
	mutation    *EpisodeMutation
	retryConfig sql.RetryConfig
}

// SetSeasonID sets the "season_id" field.
func (_u *EpisodeUpdateOne) SetSeasonID(v int64) *EpisodeUpdateOne {
	_u.mutation.SetSeasonID(v)
	return _u
}

// SetNillableSeasonID sets the "season_id" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableSeasonID(v *int64) *EpisodeUpdateOne {
	if v != nil {
		_u.SetSeasonID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *EpisodeUpdateOne) SetTitle(v string) *EpisodeUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableTitle(v *string) *EpisodeUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAirDate sets the "air_date" field.
func (_u *EpisodeUpdateOne) SetAirDate(v time.Time) *EpisodeUpdateOne {
	_u.mutation.SetAirDate(v)
	return _u
}

// SetNillableAirDate sets the "air_date" field if the given value is not nil.
func (_u *EpisodeUpdateOne) SetNillableAirDate(v *time.Time) *EpisodeUpdateOne {
	if v != nil {
		_u.SetAirDate(*v)
	}
	return _u
}

// SetSeason sets the "season" edge to the Season entity.
func (_u *EpisodeUpdateOne) SetSeason(v *Season) *EpisodeUpdateOne {
	return _u.SetSeasonID(v.ID)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_u *EpisodeUpdateOne) Mutation() *EpisodeMutation {
	return _u.mutation
}

// ClearSeason clears the "season" edge to the Season entity.
func (_u *EpisodeUpdateOne) ClearSeason() *EpisodeUpdateOne {
	_u.mutation.ClearSeason()
	return _u
}

// Where appends a list predicates to the EpisodeUpdate builder.
func (_u *EpisodeUpdateOne) Where(ps ...predicate.Episode) *EpisodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EpisodeUpdateOne) Select(field string, fields ...string) *EpisodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Episode entity.
func (_u *EpisodeUpdateOne) Save(ctx context.Context) (*Episode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EpisodeUpdateOne) SaveX(ctx context.Context) *Episode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EpisodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EpisodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EpisodeUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := episode.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Episode.title": %w`, err)}
		}
	}
	if _u.mutation.SeasonCleared() && len(_u.mutation.SeasonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Episode.season"`)
	}
	return nil
}

// WithRetryOptions sets the retry options for the update operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_u *EpisodeUpdateOne) WithRetryOptions(opts ...any) *EpisodeUpdateOne {
	_u.retryConfig.Options = opts
	return _u
}

func (_u *EpisodeUpdateOne) sqlSave(ctx context.Context) (_node *Episode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(episode.Table, episode.Columns, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Episode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, episode.FieldID)
		for _, f := range fields {
			if !episode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != episode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
	}
	if _u.mutation.SeasonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.RetryConfig = _u.retryConfig
	_node = &Episode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{episode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
