// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/schema/field"
)

// EpisodeCreate is the builder for creating a Episode entity.
type EpisodeCreate struct {
	config
	mutation    *EpisodeMutation
	hooks       []Hook
	retryConfig sqlgraph.RetryConfig
}

// SetSeasonID sets the "season_id" field.
func (_c *EpisodeCreate) SetSeasonID(v int64) *EpisodeCreate {
	_c.mutation.SetSeasonID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *EpisodeCreate) SetTitle(v string) *EpisodeCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetAirDate sets the "air_date" field.
func (_c *EpisodeCreate) SetAirDate(v time.Time) *EpisodeCreate {
	_c.mutation.SetAirDate(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EpisodeCreate) SetID(v int64) *EpisodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSeason sets the "season" edge to the Season entity.
func (_c *EpisodeCreate) SetSeason(v *Season) *EpisodeCreate {
	return _c.SetSeasonID(v.ID)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_c *EpisodeCreate) Mutation() *EpisodeMutation {
	return _c.mutation
}

// Save creates the Episode in the database.
func (_c *EpisodeCreate) Save(ctx context.Context) (*Episode, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EpisodeCreate) SaveX(ctx context.Context) *Episode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EpisodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EpisodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EpisodeCreate) check() error {
	if _, ok := _c.mutation.SeasonID(); !ok {
		return &ValidationError{Name: "season_id", err: errors.New(`ent: missing required field "Episode.season_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Episode.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := episode.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Episode.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AirDate(); !ok {
		return &ValidationError{Name: "air_date", err: errors.New(`ent: missing required field "Episode.air_date"`)}
	}
	if len(_c.mutation.SeasonIDs()) == 0 {
		return &ValidationError{Name: "season", err: errors.New(`ent: missing required edge "Episode.season"`)}
	}
	return nil
}

func (_c *EpisodeCreate) sqlSave(ctx context.Context) (*Episode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EpisodeCreate) createSpec() (*Episode, *sqlgraph.CreateSpec) {
	var (
		_node = &Episode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(episode.Table, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64))
	)
	_spec.RetryConfig = _c.retryConfig
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.AirDate(); ok {
		_spec.SetField(episode.FieldAirDate, field.TypeTime, value)
		_node.AirDate = value
	}
	if nodes := _c.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.SeasonTable,
			Columns: []string{episode.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeasonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WithRetryOptions sets the retry options for the create operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_c *EpisodeCreate) WithRetryOptions(opts ...any) *EpisodeCreate {
	_c.retryConfig.Options = opts
	return _c
}

// EpisodeCreateBulk is the builder for creating many Episode entities in bulk.
type EpisodeCreateBulk struct {
	config
	err         error
	builders    []*EpisodeCreate
	retryConfig sqlgraph.RetryConfig
}

// Save creates the Episode entities in the database.
func (_c *EpisodeCreateBulk) Save(ctx context.Context) ([]*Episode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Episode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EpisodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.RetryConfig = _c.retryConfig
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EpisodeCreateBulk) SaveX(ctx context.Context) []*Episode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EpisodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EpisodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// WithRetryOptions sets the retry options for the bulk create operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_c *EpisodeCreateBulk) WithRetryOptions(opts ...any) *EpisodeCreateBulk {
	_c.retryConfig.Options = opts
	return _c
}
