// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/predicate"
	"entgo.io/ent/schema/field"
)

// EpisodeDelete is the builder for deleting a Episode entity.
type EpisodeDelete struct {
	config
	hooks       []Hook
	mutation    *EpisodeMutation
	retryConfig sql.RetryConfig
}

// Where appends a list predicates to the EpisodeDelete builder.
func (_d *EpisodeDelete) Where(ps ...predicate.Episode) *EpisodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EpisodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EpisodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EpisodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(episode.Table, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64))
	_spec.RetryConfig = _d.retryConfig
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WithRetryOptions sets the retry options for the delete operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_d *EpisodeDelete) WithRetryOptions(opts ...any) *EpisodeDelete {
	_d.retryConfig.Options = opts
	return _d
}

// EpisodeDeleteOne is the builder for deleting a single Episode entity.
type EpisodeDeleteOne struct {
	_d *EpisodeDelete
}

// Where appends a list predicates to the EpisodeDelete builder.
func (_d *EpisodeDeleteOne) Where(ps ...predicate.Episode) *EpisodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EpisodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{episode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EpisodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
