// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/schema"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	episodeFields := schema.Episode{}.Fields()
	_ = episodeFields
	// episodeDescTitle is the schema descriptor for title field.
	episodeDescTitle := episodeFields[2].Descriptor()
	// episode.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	episode.TitleValidator = episodeDescTitle.Validators[0].(func(string) error)
	seasonFields := schema.Season{}.Fields()
	_ = seasonFields
	// seasonDescTitle is the schema descriptor for title field.
	seasonDescTitle := seasonFields[2].Descriptor()
	// season.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	season.TitleValidator = seasonDescTitle.Validators[0].(func(string) error)
	seriesFields := schema.Series{}.Fields()
	_ = seriesFields
	// seriesDescTitle is the schema descriptor for title field.
	seriesDescTitle := seriesFields[1].Descriptor()
	// series.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	series.TitleValidator = seriesDescTitle.Validators[0].(func(string) error)
}
