// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
	"entgo.io/ent/schema/field"
)

// SeasonCreate is the builder for creating a Season entity.
type SeasonCreate struct {
	config
	mutation    *SeasonMutation
	hooks       []Hook
	retryConfig sql.RetryConfig
}

// SetSeriesID sets the "series_id" field.
func (_c *SeasonCreate) SetSeriesID(v int64) *SeasonCreate {
	_c.mutation.SetSeriesID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SeasonCreate) SetTitle(v string) *SeasonCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetFirstAired sets the "first_aired" field.
func (_c *SeasonCreate) SetFirstAired(v time.Time) *SeasonCreate {
	_c.mutation.SetFirstAired(v)
	return _c
}

// SetLastAired sets the "last_aired" field.
func (_c *SeasonCreate) SetLastAired(v time.Time) *SeasonCreate {
	_c.mutation.SetLastAired(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SeasonCreate) SetID(v int64) *SeasonCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *SeasonCreate) SetSeries(v *Series) *SeasonCreate {
	return _c.SetSeriesID(v.ID)
}

// AddEpisodeIDs adds the "episodes" edge to the Episode entity by IDs.
func (_c *SeasonCreate) AddEpisodeIDs(ids ...int64) *SeasonCreate {
	_c.mutation.AddEpisodeIDs(ids...)
	return _c
}

// AddEpisodes adds the "episodes" edges to the Episode entity.
func (_c *SeasonCreate) AddEpisodes(v ...*Episode) *SeasonCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEpisodeIDs(ids...)
}

// Mutation returns the SeasonMutation object of the builder.
func (_c *SeasonCreate) Mutation() *SeasonMutation {
	return _c.mutation
}

// Save creates the Season in the database.
func (_c *SeasonCreate) Save(ctx context.Context) (*Season, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeasonCreate) SaveX(ctx context.Context) *Season {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeasonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeasonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeasonCreate) check() error {
	if _, ok := _c.mutation.SeriesID(); !ok {
		return &ValidationError{Name: "series_id", err: errors.New(`ent: missing required field "Season.series_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Season.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := season.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Season.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirstAired(); !ok {
		return &ValidationError{Name: "first_aired", err: errors.New(`ent: missing required field "Season.first_aired"`)}
	}
	if _, ok := _c.mutation.LastAired(); !ok {
		return &ValidationError{Name: "last_aired", err: errors.New(`ent: missing required field "Season.last_aired"`)}
	}
	if len(_c.mutation.SeriesIDs()) == 0 {
		return &ValidationError{Name: "series", err: errors.New(`ent: missing required edge "Season.series"`)}
	}
	return nil
}

func (_c *SeasonCreate) sqlSave(ctx context.Context) (*Season, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeasonCreate) createSpec() (*Season, *sqlgraph.CreateSpec) {
	var (
		_node = &Season{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(season.Table, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64))
	)
	_spec.RetryConfig = _c.retryConfig
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(season.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.FirstAired(); ok {
		_spec.SetField(season.FieldFirstAired, field.TypeTime, value)
		_node.FirstAired = value
	}
	if value, ok := _c.mutation.LastAired(); ok {
		_spec.SetField(season.FieldLastAired, field.TypeTime, value)
		_node.LastAired = value
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.SeriesTable,
			Columns: []string{season.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeriesID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EpisodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WithRetryOptions sets the retry options for the create operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_c *SeasonCreate) WithRetryOptions(opts ...any) *SeasonCreate {
	_c.retryConfig.Options = opts
	return _c
}

// SeasonCreateBulk is the builder for creating many Season entities in bulk.
type SeasonCreateBulk struct {
	config
	err         error
	builders    []*SeasonCreate
	retryConfig sql.RetryConfig
}

// Save creates the Season entities in the database.
func (_c *SeasonCreateBulk) Save(ctx context.Context) ([]*Season, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Season, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeasonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.RetryConfig = _c.retryConfig
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeasonCreateBulk) SaveX(ctx context.Context) []*Season {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeasonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeasonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// WithRetryOptions sets the retry options for the bulk create operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_c *SeasonCreateBulk) WithRetryOptions(opts ...any) *SeasonCreateBulk {
	_c.retryConfig.Options = opts
	return _c
}
