// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
)

// Season is the model entity for the Season schema.
type Season struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SeriesID holds the value of the "series_id" field.
	SeriesID int64 `json:"series_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// FirstAired holds the value of the "first_aired" field.
	FirstAired time.Time `json:"first_aired,omitempty"`
	// LastAired holds the value of the "last_aired" field.
	LastAired time.Time `json:"last_aired,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SeasonQuery when eager-loading is set.
	Edges        SeasonEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SeasonEdges holds the relations/edges for other nodes in the graph.
type SeasonEdges struct {
	// Series holds the value of the series edge.
	Series *Series `json:"series,omitempty"`
	// Episodes holds the value of the episodes edge.
	Episodes []*Episode `json:"episodes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SeriesOrErr returns the Series value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SeasonEdges) SeriesOrErr() (*Series, error) {
	if e.Series != nil {
		return e.Series, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: series.Label}
	}
	return nil, &NotLoadedError{edge: "series"}
}

// EpisodesOrErr returns the Episodes value or an error if the edge
// was not loaded in eager-loading.
func (e SeasonEdges) EpisodesOrErr() ([]*Episode, error) {
	if e.loadedTypes[1] {
		return e.Episodes, nil
	}
	return nil, &NotLoadedError{edge: "episodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Season) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case season.FieldID, season.FieldSeriesID:
			values[i] = new(sql.NullInt64)
		case season.FieldTitle:
			values[i] = new(sql.NullString)
		case season.FieldFirstAired, season.FieldLastAired:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Season fields.
func (_m *Season) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case season.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case season.FieldSeriesID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field series_id", values[i])
			} else if value.Valid {
				_m.SeriesID = value.Int64
			}
		case season.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case season.FieldFirstAired:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_aired", values[i])
			} else if value.Valid {
				_m.FirstAired = value.Time
			}
		case season.FieldLastAired:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_aired", values[i])
			} else if value.Valid {
				_m.LastAired = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Season.
// This includes values selected through modifiers, order, etc.
func (_m *Season) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySeries queries the "series" edge of the Season entity.
func (_m *Season) QuerySeries() *SeriesQuery {
	return NewSeasonClient(_m.config).QuerySeries(_m)
}

// QueryEpisodes queries the "episodes" edge of the Season entity.
func (_m *Season) QueryEpisodes() *EpisodeQuery {
	return NewSeasonClient(_m.config).QueryEpisodes(_m)
}

// Update returns a builder for updating this Season.
// Note that you need to call Season.Unwrap() before calling this method if this Season
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Season) Update() *SeasonUpdateOne {
	return NewSeasonClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Season entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Season) Unwrap() *Season {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Season is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Season) String() string {
	var builder strings.Builder
	builder.WriteString("Season(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("series_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeriesID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("first_aired=")
	builder.WriteString(_m.FirstAired.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_aired=")
	builder.WriteString(_m.LastAired.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Seasons is a parsable slice of Season.
type Seasons []*Season
