// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/predicate"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
	"entgo.io/ent/schema/field"
)

// SeasonQuery is the builder for querying Season entities.
type SeasonQuery struct {
	config
	ctx          *QueryContext
	order        []season.OrderOption
	inters       []Interceptor
	predicates   []predicate.Season
	withSeries   *SeriesQuery
	withEpisodes *EpisodeQuery
	retryConfig  sql.RetryConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SeasonQuery builder.
func (_q *SeasonQuery) Where(ps ...predicate.Season) *SeasonQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SeasonQuery) Limit(limit int) *SeasonQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SeasonQuery) Offset(offset int) *SeasonQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SeasonQuery) Unique(unique bool) *SeasonQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SeasonQuery) Order(o ...season.OrderOption) *SeasonQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySeries chains the current query on the "series" edge.
func (_q *SeasonQuery) QuerySeries() *SeriesQuery {
	query := (&SeriesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(season.Table, season.FieldID, selector),
			sqlgraph.To(series.Table, series.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, season.SeriesTable, season.SeriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEpisodes chains the current query on the "episodes" edge.
func (_q *SeasonQuery) QueryEpisodes() *EpisodeQuery {
	query := (&EpisodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(season.Table, season.FieldID, selector),
			sqlgraph.To(episode.Table, episode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, season.EpisodesTable, season.EpisodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Season entity from the query.
// Returns a *NotFoundError when no Season was found.
func (_q *SeasonQuery) First(ctx context.Context) (*Season, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{season.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SeasonQuery) FirstX(ctx context.Context) *Season {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Season ID from the query.
// Returns a *NotFoundError when no Season ID was found.
func (_q *SeasonQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{season.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SeasonQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Season entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Season entity is found.
// Returns a *NotFoundError when no Season entities are found.
func (_q *SeasonQuery) Only(ctx context.Context) (*Season, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{season.Label}
	default:
		return nil, &NotSingularError{season.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SeasonQuery) OnlyX(ctx context.Context) *Season {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Season ID in the query.
// Returns a *NotSingularError when more than one Season ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SeasonQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{season.Label}
	default:
		err = &NotSingularError{season.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SeasonQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Seasons.
func (_q *SeasonQuery) All(ctx context.Context) ([]*Season, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Season, *SeasonQuery]()
	return withInterceptors[[]*Season](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SeasonQuery) AllX(ctx context.Context) []*Season {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Season IDs.
func (_q *SeasonQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(season.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SeasonQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SeasonQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SeasonQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SeasonQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SeasonQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SeasonQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SeasonQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SeasonQuery) Clone() *SeasonQuery {
	if _q == nil {
		return nil
	}
	return &SeasonQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]season.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Season{}, _q.predicates...),
		withSeries:   _q.withSeries.Clone(),
		withEpisodes: _q.withEpisodes.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSeries tells the query-builder to eager-load the nodes that are connected to
// the "series" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SeasonQuery) WithSeries(opts ...func(*SeriesQuery)) *SeasonQuery {
	query := (&SeriesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSeries = query
	return _q
}

// WithEpisodes tells the query-builder to eager-load the nodes that are connected to
// the "episodes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SeasonQuery) WithEpisodes(opts ...func(*EpisodeQuery)) *SeasonQuery {
	query := (&EpisodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEpisodes = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SeriesID int64 `json:"series_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Season.Query().
//		GroupBy(season.FieldSeriesID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SeasonQuery) GroupBy(field string, fields ...string) *SeasonGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SeasonGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = season.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SeriesID int64 `json:"series_id,omitempty"`
//	}
//
//	client.Season.Query().
//		Select(season.FieldSeriesID).
//		Scan(ctx, &v)
func (_q *SeasonQuery) Select(fields ...string) *SeasonSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SeasonSelect{SeasonQuery: _q}
	sbuild.label = season.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SeasonSelect configured with the given aggregations.
func (_q *SeasonQuery) Aggregate(fns ...AggregateFunc) *SeasonSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SeasonQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !season.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SeasonQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Season, error) {
	var (
		nodes       = []*Season{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSeries != nil,
			_q.withEpisodes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Season).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Season{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.RetryConfig = _q.retryConfig
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSeries; query != nil {
		if err := _q.loadSeries(ctx, query, nodes, nil,
			func(n *Season, e *Series) { n.Edges.Series = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEpisodes; query != nil {
		if err := _q.loadEpisodes(ctx, query, nodes,
			func(n *Season) { n.Edges.Episodes = []*Episode{} },
			func(n *Season, e *Episode) { n.Edges.Episodes = append(n.Edges.Episodes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SeasonQuery) loadSeries(ctx context.Context, query *SeriesQuery, nodes []*Season, init func(*Season), assign func(*Season, *Series)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Season)
	for i := range nodes {
		fk := nodes[i].SeriesID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(series.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "series_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SeasonQuery) loadEpisodes(ctx context.Context, query *EpisodeQuery, nodes []*Season, init func(*Season), assign func(*Season, *Episode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Season)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(episode.FieldSeasonID)
	}
	query.Where(predicate.Episode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(season.EpisodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SeasonID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "season_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SeasonQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.RetryConfig = _q.retryConfig
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SeasonQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(season.Table, season.Columns, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, season.FieldID)
		for i := range fields {
			if fields[i] != season.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSeries != nil {
			_spec.Node.AddColumnOnce(season.FieldSeriesID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SeasonQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(season.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = season.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithRetryOptions sets the retry options for the query operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_q *SeasonQuery) WithRetryOptions(opts ...any) *SeasonQuery {
	_q.retryConfig.Options = opts
	return _q
}

// SeasonGroupBy is the group-by builder for Season entities.
type SeasonGroupBy struct {
	selector
	build *SeasonQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SeasonGroupBy) Aggregate(fns ...AggregateFunc) *SeasonGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SeasonGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeasonQuery, *SeasonGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SeasonGroupBy) sqlScan(ctx context.Context, root *SeasonQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SeasonSelect is the builder for selecting fields of Season entities.
type SeasonSelect struct {
	*SeasonQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SeasonSelect) Aggregate(fns ...AggregateFunc) *SeasonSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SeasonSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeasonQuery, *SeasonSelect](ctx, _s.SeasonQuery, _s, _s.inters, v)
}

func (_s *SeasonSelect) sqlScan(ctx context.Context, root *SeasonQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
