// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/episode"
	"entgo.io/ent/examples/ydb/ent/predicate"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
	"entgo.io/ent/schema/field"
)

// SeasonUpdate is the builder for updating Season entities.
type SeasonUpdate struct {
	config
	hooks       []Hook
	mutation    *SeasonMutation
	retryConfig sql.RetryConfig
}

// Where appends a list predicates to the SeasonUpdate builder.
func (_u *SeasonUpdate) Where(ps ...predicate.Season) *SeasonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *SeasonUpdate) SetSeriesID(v int64) *SeasonUpdate {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *SeasonUpdate) SetNillableSeriesID(v *int64) *SeasonUpdate {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SeasonUpdate) SetTitle(v string) *SeasonUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SeasonUpdate) SetNillableTitle(v *string) *SeasonUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetFirstAired sets the "first_aired" field.
func (_u *SeasonUpdate) SetFirstAired(v time.Time) *SeasonUpdate {
	_u.mutation.SetFirstAired(v)
	return _u
}

// SetNillableFirstAired sets the "first_aired" field if the given value is not nil.
func (_u *SeasonUpdate) SetNillableFirstAired(v *time.Time) *SeasonUpdate {
	if v != nil {
		_u.SetFirstAired(*v)
	}
	return _u
}

// SetLastAired sets the "last_aired" field.
func (_u *SeasonUpdate) SetLastAired(v time.Time) *SeasonUpdate {
	_u.mutation.SetLastAired(v)
	return _u
}

// SetNillableLastAired sets the "last_aired" field if the given value is not nil.
func (_u *SeasonUpdate) SetNillableLastAired(v *time.Time) *SeasonUpdate {
	if v != nil {
		_u.SetLastAired(*v)
	}
	return _u
}

// SetSeries sets the "series" edge to the Series entity.
func (_u *SeasonUpdate) SetSeries(v *Series) *SeasonUpdate {
	return _u.SetSeriesID(v.ID)
}

// AddEpisodeIDs adds the "episodes" edge to the Episode entity by IDs.
func (_u *SeasonUpdate) AddEpisodeIDs(ids ...int64) *SeasonUpdate {
	_u.mutation.AddEpisodeIDs(ids...)
	return _u
}

// AddEpisodes adds the "episodes" edges to the Episode entity.
func (_u *SeasonUpdate) AddEpisodes(v ...*Episode) *SeasonUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEpisodeIDs(ids...)
}

// Mutation returns the SeasonMutation object of the builder.
func (_u *SeasonUpdate) Mutation() *SeasonMutation {
	return _u.mutation
}

// ClearSeries clears the "series" edge to the Series entity.
func (_u *SeasonUpdate) ClearSeries() *SeasonUpdate {
	_u.mutation.ClearSeries()
	return _u
}

// ClearEpisodes clears all "episodes" edges to the Episode entity.
func (_u *SeasonUpdate) ClearEpisodes() *SeasonUpdate {
	_u.mutation.ClearEpisodes()
	return _u
}

// RemoveEpisodeIDs removes the "episodes" edge to Episode entities by IDs.
func (_u *SeasonUpdate) RemoveEpisodeIDs(ids ...int64) *SeasonUpdate {
	_u.mutation.RemoveEpisodeIDs(ids...)
	return _u
}

// RemoveEpisodes removes "episodes" edges to Episode entities.
func (_u *SeasonUpdate) RemoveEpisodes(v ...*Episode) *SeasonUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEpisodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SeasonUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeasonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SeasonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeasonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeasonUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := season.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Season.title": %w`, err)}
		}
	}
	if _u.mutation.SeriesCleared() && len(_u.mutation.SeriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Season.series"`)
	}
	return nil
}

// WithRetryOptions sets the retry options for the update operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_u *SeasonUpdate) WithRetryOptions(opts ...any) *SeasonUpdate {
	_u.retryConfig.Options = opts
	return _u
}

func (_u *SeasonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(season.Table, season.Columns, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(season.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstAired(); ok {
		_spec.SetField(season.FieldFirstAired, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastAired(); ok {
		_spec.SetField(season.FieldLastAired, field.TypeTime, value)
	}
	if _u.mutation.SeriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.SeriesTable,
			Columns: []string{season.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.SeriesTable,
			Columns: []string{season.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEpisodesIDs(); len(nodes) > 0 && !_u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EpisodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.RetryConfig = _u.retryConfig
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if sqlgraph.IsNotFound(err) {
			err = &NotFoundError{season.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SeasonUpdateOne is the builder for updating a single Season entity.
type SeasonUpdateOne struct {
	config
	fields      []string
	hooks       []Hook
	mutation    *SeasonMutation
	retryConfig sql.RetryConfig
}

// SetSeriesID sets the "series_id" field.
func (_u *SeasonUpdateOne) SetSeriesID(v int64) *SeasonUpdateOne {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *SeasonUpdateOne) SetNillableSeriesID(v *int64) *SeasonUpdateOne {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SeasonUpdateOne) SetTitle(v string) *SeasonUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SeasonUpdateOne) SetNillableTitle(v *string) *SeasonUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetFirstAired sets the "first_aired" field.
func (_u *SeasonUpdateOne) SetFirstAired(v time.Time) *SeasonUpdateOne {
	_u.mutation.SetFirstAired(v)
	return _u
}

// SetNillableFirstAired sets the "first_aired" field if the given value is not nil.
func (_u *SeasonUpdateOne) SetNillableFirstAired(v *time.Time) *SeasonUpdateOne {
	if v != nil {
		_u.SetFirstAired(*v)
	}
	return _u
}

// SetLastAired sets the "last_aired" field.
func (_u *SeasonUpdateOne) SetLastAired(v time.Time) *SeasonUpdateOne {
	_u.mutation.SetLastAired(v)
	return _u
}

// SetNillableLastAired sets the "last_aired" field if the given value is not nil.
func (_u *SeasonUpdateOne) SetNillableLastAired(v *time.Time) *SeasonUpdateOne {
	if v != nil {
		_u.SetLastAired(*v)
	}
	return _u
}

// SetSeries sets the "series" edge to the Series entity.
func (_u *SeasonUpdateOne) SetSeries(v *Series) *SeasonUpdateOne {
	return _u.SetSeriesID(v.ID)
}

// AddEpisodeIDs adds the "episodes" edge to the Episode entity by IDs.
func (_u *SeasonUpdateOne) AddEpisodeIDs(ids ...int64) *SeasonUpdateOne {
	_u.mutation.AddEpisodeIDs(ids...)
	return _u
}

// AddEpisodes adds the "episodes" edges to the Episode entity.
func (_u *SeasonUpdateOne) AddEpisodes(v ...*Episode) *SeasonUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEpisodeIDs(ids...)
}

// Mutation returns the SeasonMutation object of the builder.
func (_u *SeasonUpdateOne) Mutation() *SeasonMutation {
	return _u.mutation
}

// ClearSeries clears the "series" edge to the Series entity.
func (_u *SeasonUpdateOne) ClearSeries() *SeasonUpdateOne {
	_u.mutation.ClearSeries()
	return _u
}

// ClearEpisodes clears all "episodes" edges to the Episode entity.
func (_u *SeasonUpdateOne) ClearEpisodes() *SeasonUpdateOne {
	_u.mutation.ClearEpisodes()
	return _u
}

// RemoveEpisodeIDs removes the "episodes" edge to Episode entities by IDs.
func (_u *SeasonUpdateOne) RemoveEpisodeIDs(ids ...int64) *SeasonUpdateOne {
	_u.mutation.RemoveEpisodeIDs(ids...)
	return _u
}

// RemoveEpisodes removes "episodes" edges to Episode entities.
func (_u *SeasonUpdateOne) RemoveEpisodes(v ...*Episode) *SeasonUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEpisodeIDs(ids...)
}

// Where appends a list predicates to the SeasonUpdate builder.
func (_u *SeasonUpdateOne) Where(ps ...predicate.Season) *SeasonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SeasonUpdateOne) Select(field string, fields ...string) *SeasonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Season entity.
func (_u *SeasonUpdateOne) Save(ctx context.Context) (*Season, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeasonUpdateOne) SaveX(ctx context.Context) *Season {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SeasonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeasonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeasonUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := season.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Season.title": %w`, err)}
		}
	}
	if _u.mutation.SeriesCleared() && len(_u.mutation.SeriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Season.series"`)
	}
	return nil
}

// WithRetryOptions sets the retry options for the update operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_u *SeasonUpdateOne) WithRetryOptions(opts ...any) *SeasonUpdateOne {
	_u.retryConfig.Options = opts
	return _u
}

func (_u *SeasonUpdateOne) sqlSave(ctx context.Context) (_node *Season, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(season.Table, season.Columns, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Season.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, season.FieldID)
		for _, f := range fields {
			if !season.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != season.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(season.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstAired(); ok {
		_spec.SetField(season.FieldFirstAired, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastAired(); ok {
		_spec.SetField(season.FieldLastAired, field.TypeTime, value)
	}
	if _u.mutation.SeriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.SeriesTable,
			Columns: []string{season.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.SeriesTable,
			Columns: []string{season.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEpisodesIDs(); len(nodes) > 0 && !_u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EpisodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.EpisodesTable,
			Columns: []string{season.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.RetryConfig = _u.retryConfig
	_node = &Season{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if sqlgraph.IsNotFound(err) {
			err = &NotFoundError{season.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
