// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/predicate"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
	"entgo.io/ent/schema/field"
)

// SeriesUpdate is the builder for updating Series entities.
type SeriesUpdate struct {
	config
	hooks       []Hook
	mutation    *SeriesMutation
	retryConfig sql.RetryConfig
}

// Where appends a list predicates to the SeriesUpdate builder.
func (_u *SeriesUpdate) Where(ps ...predicate.Series) *SeriesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SeriesUpdate) SetTitle(v string) *SeriesUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableTitle(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetInfo sets the "info" field.
func (_u *SeriesUpdate) SetInfo(v string) *SeriesUpdate {
	_u.mutation.SetInfo(v)
	return _u
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableInfo(v *string) *SeriesUpdate {
	if v != nil {
		_u.SetInfo(*v)
	}
	return _u
}

// ClearInfo clears the value of the "info" field.
func (_u *SeriesUpdate) ClearInfo() *SeriesUpdate {
	_u.mutation.ClearInfo()
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *SeriesUpdate) SetReleaseDate(v time.Time) *SeriesUpdate {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *SeriesUpdate) SetNillableReleaseDate(v *time.Time) *SeriesUpdate {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// AddSeasonIDs adds the "seasons" edge to the Season entity by IDs.
func (_u *SeriesUpdate) AddSeasonIDs(ids ...int64) *SeriesUpdate {
	_u.mutation.AddSeasonIDs(ids...)
	return _u
}

// AddSeasons adds the "seasons" edges to the Season entity.
func (_u *SeriesUpdate) AddSeasons(v ...*Season) *SeriesUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeasonIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_u *SeriesUpdate) Mutation() *SeriesMutation {
	return _u.mutation
}

// ClearSeasons clears all "seasons" edges to the Season entity.
func (_u *SeriesUpdate) ClearSeasons() *SeriesUpdate {
	_u.mutation.ClearSeasons()
	return _u
}

// RemoveSeasonIDs removes the "seasons" edge to Season entities by IDs.
func (_u *SeriesUpdate) RemoveSeasonIDs(ids ...int64) *SeriesUpdate {
	_u.mutation.RemoveSeasonIDs(ids...)
	return _u
}

// RemoveSeasons removes "seasons" edges to Season entities.
func (_u *SeriesUpdate) RemoveSeasons(v ...*Season) *SeriesUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeasonIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SeriesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SeriesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeriesUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := series.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Series.title": %w`, err)}
		}
	}
	return nil
}

// WithRetryOptions sets the retry options for the update operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_u *SeriesUpdate) WithRetryOptions(opts ...any) *SeriesUpdate {
	_u.retryConfig.Options = opts
	return _u
}

func (_u *SeriesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(series.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Info(); ok {
		_spec.SetField(series.FieldInfo, field.TypeString, value)
	}
	if _u.mutation.InfoCleared() {
		_spec.ClearField(series.FieldInfo, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(series.FieldReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.SeasonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeasonsIDs(); len(nodes) > 0 && !_u.mutation.SeasonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeasonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.RetryConfig = _u.retryConfig
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SeriesUpdateOne is the builder for updating a single Series entity.
type SeriesUpdateOne struct {
	config
	fields      []string
	hooks       []Hook
	mutation    *SeriesMutation
	retryConfig sql.RetryConfig
}

// SetTitle sets the "title" field.
func (_u *SeriesUpdateOne) SetTitle(v string) *SeriesUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableTitle(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetInfo sets the "info" field.
func (_u *SeriesUpdateOne) SetInfo(v string) *SeriesUpdateOne {
	_u.mutation.SetInfo(v)
	return _u
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableInfo(v *string) *SeriesUpdateOne {
	if v != nil {
		_u.SetInfo(*v)
	}
	return _u
}

// ClearInfo clears the value of the "info" field.
func (_u *SeriesUpdateOne) ClearInfo() *SeriesUpdateOne {
	_u.mutation.ClearInfo()
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *SeriesUpdateOne) SetReleaseDate(v time.Time) *SeriesUpdateOne {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *SeriesUpdateOne) SetNillableReleaseDate(v *time.Time) *SeriesUpdateOne {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// AddSeasonIDs adds the "seasons" edge to the Season entity by IDs.
func (_u *SeriesUpdateOne) AddSeasonIDs(ids ...int64) *SeriesUpdateOne {
	_u.mutation.AddSeasonIDs(ids...)
	return _u
}

// AddSeasons adds the "seasons" edges to the Season entity.
func (_u *SeriesUpdateOne) AddSeasons(v ...*Season) *SeriesUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeasonIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_u *SeriesUpdateOne) Mutation() *SeriesMutation {
	return _u.mutation
}

// ClearSeasons clears all "seasons" edges to the Season entity.
func (_u *SeriesUpdateOne) ClearSeasons() *SeriesUpdateOne {
	_u.mutation.ClearSeasons()
	return _u
}

// RemoveSeasonIDs removes the "seasons" edge to Season entities by IDs.
func (_u *SeriesUpdateOne) RemoveSeasonIDs(ids ...int64) *SeriesUpdateOne {
	_u.mutation.RemoveSeasonIDs(ids...)
	return _u
}

// RemoveSeasons removes "seasons" edges to Season entities.
func (_u *SeriesUpdateOne) RemoveSeasons(v ...*Season) *SeriesUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeasonIDs(ids...)
}

// Where appends a list predicates to the SeriesUpdate builder.
func (_u *SeriesUpdateOne) Where(ps ...predicate.Series) *SeriesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SeriesUpdateOne) Select(field string, fields ...string) *SeriesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Series entity.
func (_u *SeriesUpdateOne) Save(ctx context.Context) (*Series, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesUpdateOne) SaveX(ctx context.Context) *Series {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SeriesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeriesUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := series.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Series.title": %w`, err)}
		}
	}
	return nil
}

// WithRetryOptions sets the retry options for the update operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_u *SeriesUpdateOne) WithRetryOptions(opts ...any) *SeriesUpdateOne {
	_u.retryConfig.Options = opts
	return _u
}

func (_u *SeriesUpdateOne) sqlSave(ctx context.Context) (_node *Series, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Series.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, series.FieldID)
		for _, f := range fields {
			if !series.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != series.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(series.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Info(); ok {
		_spec.SetField(series.FieldInfo, field.TypeString, value)
	}
	if _u.mutation.InfoCleared() {
		_spec.ClearField(series.FieldInfo, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(series.FieldReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.SeasonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeasonsIDs(); len(nodes) > 0 && !_u.mutation.SeasonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeasonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.RetryConfig = _u.retryConfig
	_node = &Series{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
