// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
	"entgo.io/ent/schema/field"
)

// SeriesCreate is the builder for creating a Series entity.
type SeriesCreate struct {
	config
	mutation    *SeriesMutation
	hooks       []Hook
	retryConfig sqlgraph.RetryConfig
}

// SetTitle sets the "title" field.
func (_c *SeriesCreate) SetTitle(v string) *SeriesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetInfo sets the "info" field.
func (_c *SeriesCreate) SetInfo(v string) *SeriesCreate {
	_c.mutation.SetInfo(v)
	return _c
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableInfo(v *string) *SeriesCreate {
	if v != nil {
		_c.SetInfo(*v)
	}
	return _c
}

// SetReleaseDate sets the "release_date" field.
func (_c *SeriesCreate) SetReleaseDate(v time.Time) *SeriesCreate {
	_c.mutation.SetReleaseDate(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SeriesCreate) SetID(v int64) *SeriesCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSeasonIDs adds the "seasons" edge to the Season entity by IDs.
func (_c *SeriesCreate) AddSeasonIDs(ids ...int64) *SeriesCreate {
	_c.mutation.AddSeasonIDs(ids...)
	return _c
}

// AddSeasons adds the "seasons" edges to the Season entity.
func (_c *SeriesCreate) AddSeasons(v ...*Season) *SeriesCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSeasonIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_c *SeriesCreate) Mutation() *SeriesMutation {
	return _c.mutation
}

// Save creates the Series in the database.
func (_c *SeriesCreate) Save(ctx context.Context) (*Series, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeriesCreate) SaveX(ctx context.Context) *Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeriesCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Series.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := series.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Series.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReleaseDate(); !ok {
		return &ValidationError{Name: "release_date", err: errors.New(`ent: missing required field "Series.release_date"`)}
	}
	return nil
}

func (_c *SeriesCreate) sqlSave(ctx context.Context) (*Series, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeriesCreate) createSpec() (*Series, *sqlgraph.CreateSpec) {
	var (
		_node = &Series{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(series.Table, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64))
	)
	_spec.RetryConfig = _c.retryConfig
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(series.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Info(); ok {
		_spec.SetField(series.FieldInfo, field.TypeString, value)
		_node.Info = value
	}
	if value, ok := _c.mutation.ReleaseDate(); ok {
		_spec.SetField(series.FieldReleaseDate, field.TypeTime, value)
		_node.ReleaseDate = value
	}
	if nodes := _c.mutation.SeasonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeasonsTable,
			Columns: []string{series.SeasonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WithRetryOptions sets the retry options for the create operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_c *SeriesCreate) WithRetryOptions(opts ...any) *SeriesCreate {
	_c.retryConfig.Options = opts
	return _c
}

// SeriesCreateBulk is the builder for creating many Series entities in bulk.
type SeriesCreateBulk struct {
	config
	err         error
	builders    []*SeriesCreate
	retryConfig sqlgraph.RetryConfig
}

// Save creates the Series entities in the database.
func (_c *SeriesCreateBulk) Save(ctx context.Context) ([]*Series, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Series, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeriesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.RetryConfig = _c.retryConfig
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeriesCreateBulk) SaveX(ctx context.Context) []*Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// WithRetryOptions sets the retry options for the bulk create operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_c *SeriesCreateBulk) WithRetryOptions(opts ...any) *SeriesCreateBulk {
	_c.retryConfig.Options = opts
	return _c
}
