// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/examples/ydb/ent/predicate"
	"entgo.io/ent/examples/ydb/ent/season"
	"entgo.io/ent/examples/ydb/ent/series"
	"entgo.io/ent/schema/field"
)

// SeriesQuery is the builder for querying Series entities.
type SeriesQuery struct {
	config
	ctx         *QueryContext
	order       []series.OrderOption
	inters      []Interceptor
	predicates  []predicate.Series
	withSeasons *SeasonQuery
	retryConfig sql.RetryConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SeriesQuery builder.
func (_q *SeriesQuery) Where(ps ...predicate.Series) *SeriesQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SeriesQuery) Limit(limit int) *SeriesQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SeriesQuery) Offset(offset int) *SeriesQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SeriesQuery) Unique(unique bool) *SeriesQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SeriesQuery) Order(o ...series.OrderOption) *SeriesQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySeasons chains the current query on the "seasons" edge.
func (_q *SeriesQuery) QuerySeasons() *SeasonQuery {
	query := (&SeasonClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(series.Table, series.FieldID, selector),
			sqlgraph.To(season.Table, season.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, series.SeasonsTable, series.SeasonsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Series entity from the query.
// Returns a *NotFoundError when no Series was found.
func (_q *SeriesQuery) First(ctx context.Context) (*Series, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{series.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SeriesQuery) FirstX(ctx context.Context) *Series {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Series ID from the query.
// Returns a *NotFoundError when no Series ID was found.
func (_q *SeriesQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{series.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SeriesQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Series entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Series entity is found.
// Returns a *NotFoundError when no Series entities are found.
func (_q *SeriesQuery) Only(ctx context.Context) (*Series, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{series.Label}
	default:
		return nil, &NotSingularError{series.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SeriesQuery) OnlyX(ctx context.Context) *Series {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Series ID in the query.
// Returns a *NotSingularError when more than one Series ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SeriesQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{series.Label}
	default:
		err = &NotSingularError{series.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SeriesQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SeriesSlice.
func (_q *SeriesQuery) All(ctx context.Context) ([]*Series, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Series, *SeriesQuery]()
	return withInterceptors[[]*Series](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SeriesQuery) AllX(ctx context.Context) []*Series {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Series IDs.
func (_q *SeriesQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(series.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SeriesQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SeriesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SeriesQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SeriesQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SeriesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SeriesQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SeriesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SeriesQuery) Clone() *SeriesQuery {
	if _q == nil {
		return nil
	}
	return &SeriesQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]series.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.Series{}, _q.predicates...),
		withSeasons: _q.withSeasons.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSeasons tells the query-builder to eager-load the nodes that are connected to
// the "seasons" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SeriesQuery) WithSeasons(opts ...func(*SeasonQuery)) *SeriesQuery {
	query := (&SeasonClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSeasons = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Series.Query().
//		GroupBy(series.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SeriesQuery) GroupBy(field string, fields ...string) *SeriesGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SeriesGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = series.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Series.Query().
//		Select(series.FieldTitle).
//		Scan(ctx, &v)
func (_q *SeriesQuery) Select(fields ...string) *SeriesSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SeriesSelect{SeriesQuery: _q}
	sbuild.label = series.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SeriesSelect configured with the given aggregations.
func (_q *SeriesQuery) Aggregate(fns ...AggregateFunc) *SeriesSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SeriesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !series.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SeriesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Series, error) {
	var (
		nodes       = []*Series{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSeasons != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Series).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Series{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.RetryConfig = _q.retryConfig
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSeasons; query != nil {
		if err := _q.loadSeasons(ctx, query, nodes,
			func(n *Series) { n.Edges.Seasons = []*Season{} },
			func(n *Series, e *Season) { n.Edges.Seasons = append(n.Edges.Seasons, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SeriesQuery) loadSeasons(ctx context.Context, query *SeasonQuery, nodes []*Series, init func(*Series), assign func(*Series, *Season)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Series)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(season.FieldSeriesID)
	}
	query.Where(predicate.Season(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(series.SeasonsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SeriesID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "series_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SeriesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.RetryConfig = _q.retryConfig
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SeriesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, series.FieldID)
		for i := range fields {
			if fields[i] != series.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SeriesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(series.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = series.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithRetryOptions sets the retry options for the query operation.
// For YDB, these should be retry.Option values from ydb-go-sdk.
func (_q *SeriesQuery) WithRetryOptions(opts ...any) *SeriesQuery {
	_q.retryConfig.Options = opts
	return _q
}

// SeriesGroupBy is the group-by builder for Series entities.
type SeriesGroupBy struct {
	selector
	build *SeriesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SeriesGroupBy) Aggregate(fns ...AggregateFunc) *SeriesGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SeriesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeriesQuery, *SeriesGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SeriesGroupBy) sqlScan(ctx context.Context, root *SeriesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SeriesSelect is the builder for selecting fields of Series entities.
type SeriesSelect struct {
	*SeriesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SeriesSelect) Aggregate(fns ...AggregateFunc) *SeriesSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SeriesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeriesQuery, *SeriesSelect](ctx, _s.SeriesQuery, _s, _s.inters, v)
}

func (_s *SeriesSelect) sqlScan(ctx context.Context, root *SeriesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
