// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EpisodesColumns holds the columns for the "episodes" table.
	EpisodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "air_date", Type: field.TypeTime},
		{Name: "season_id", Type: field.TypeInt64},
	}
	// EpisodesTable holds the schema information for the "episodes" table.
	EpisodesTable = &schema.Table{
		Name:       "episodes",
		Columns:    EpisodesColumns,
		PrimaryKey: []*schema.Column{EpisodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "episodes_seasons_episodes",
				Columns:    []*schema.Column{EpisodesColumns[3]},
				RefColumns: []*schema.Column{SeasonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SeasonsColumns holds the columns for the "seasons" table.
	SeasonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "first_aired", Type: field.TypeTime},
		{Name: "last_aired", Type: field.TypeTime},
		{Name: "series_id", Type: field.TypeInt64},
	}
	// SeasonsTable holds the schema information for the "seasons" table.
	SeasonsTable = &schema.Table{
		Name:       "seasons",
		Columns:    SeasonsColumns,
		PrimaryKey: []*schema.Column{SeasonsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "seasons_series_seasons",
				Columns:    []*schema.Column{SeasonsColumns[4]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SeriesColumns holds the columns for the "series" table.
	SeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "info", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "release_date", Type: field.TypeTime},
	}
	// SeriesTable holds the schema information for the "series" table.
	SeriesTable = &schema.Table{
		Name:       "series",
		Columns:    SeriesColumns,
		PrimaryKey: []*schema.Column{SeriesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EpisodesTable,
		SeasonsTable,
		SeriesTable,
	}
)

func init() {
	EpisodesTable.ForeignKeys[0].RefTable = SeasonsTable
	EpisodesTable.Annotation = &entsql.Annotation{
		Table: "episodes",
	}
	SeasonsTable.ForeignKeys[0].RefTable = SeriesTable
	SeasonsTable.Annotation = &entsql.Annotation{
		Table: "seasons",
	}
	SeriesTable.Annotation = &entsql.Annotation{
		Table: "series",
	}
}
