// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Episode is the predicate function for episode builders.
type Episode func(*sql.Selector)

// Season is the predicate function for season builders.
type Season func(*sql.Selector)

// Series is the predicate function for series builders.
type Series func(*sql.Selector)
